### ISSUE TITLE
Top 20 with image looks bad.

### ISSUE THREAD

**Issue by AriMeidan** [AriMeidan/Fantasy-Knesset#15]

**Comment by AriMeidan** [comment]
Different image sizes makes top 20 ugly, not aligned well.
I'm checking now what can be done.

**Comment by Nagasaki45** [comment]
Sure they looks awful. We need to crop the images according to their bigger dimension.

**Comment by AriMeidan** [comment]
I've played with it.
Changing the height, has no affect on the outcome.
The width is limited to the width of the row.
