### ISSUE TITLE
Change the index.html so it will handle the entire 120 MKs.

### ISSUE THREAD

**Issue by AriMeidan** [AriMeidan/Fantasy-Knesset#16]

**Comment by AriMeidan** [comment]
No it gets a list of 20 - the top 20.
We need to get the rest 100.

OR

get all the 120 MKs , and split them in the template.

**Comment by Nagasaki45** [comment]
I think it will be much better if the list will be separated in advance. It is very likely that we will want to apply different behavior to the different lists (badges, etc.) in the server side.

**Comment by AriMeidan** [comment]
Agree.
Can we do it with the current view (IndexView)?

**Comment by AriMeidan** [comment]
template with no logic at new branch: rest100
