### ISSUE TITLE
Remove favicon of non facebook users

### ISSUE THREAD

**Issue by Nagasaki45** [AriMeidan/Fantasy-Knesset#25]
Now it shows a broken image tag

**Comment by AriMeidan** [comment]
Cant reproduce.
Are you updated on the template?

**Comment by Nagasaki45** [comment]
Take a look here [here](https://lh5.googleusercontent.com/-KJZ5IXqtC2M/UtPOXrbX_5I/AAAAAAAAN5w/4HssJvJci00/w1044-h587-no/Screenshot+from+2014-01-13+13%253A29%253A15.png). Next to the `Logout` button there is a placeholder for a picture. I'm logged in manually, and not from facebook and it seems that this is the problem.
BTW, the page is a candidate page I'm working on, with votes history and other details.

**Comment by AriMeidan** [comment]
Very weird because i don't have this problem even when logged as non-facebook user.
Where are you branching from?

**Comment by Nagasaki45** [comment]
From `master`.
And the problem persist on `master` too. (Chrome, Ubuntu)

**Comment by AriMeidan** [comment]
Works on FF not on Chrome.
