### ISSUE TITLE
Problems adding a candidate without a party

### ISSUE THREAD

**Issue by Nagasaki45** [AriMeidan/Fantasy-Knesset#42]
Currently adding a candidate without a party doesn't get an "independent" party. Actually, he didn't get a party at all and therefore doesn't not appear in the `candidates` view (the one with the search).
Maybe we need to hardcode an independent party to the database and force the party foreign key of each candidate in the Candidate model.

What do you think?

**Comment by AriMeidan** [comment]
Party field can be empty, so we need to translate in the templates that
none=independent.

**Comment by Nagasaki45** [comment]
I think that it will be much better to remove `null=True, blank=True` from the party foreign key of the model and add an explicit party to the DB named "Independent" or something like this.
