### ISSUE TITLE
Create the interface and logic for viewing candidates history of voting in graph

### ISSUE THREAD

**Issue by AriMeidan** [AriMeidan/Fantasy-Knesset#7]

**Comment by Nagasaki45** [comment]
@snapdragonx take a look at [django-reversion](https://github.com/etianen/django-reversion), a tool for keeping the models in version control.
I don't have any experience with this package myself but from the docs it looks perfect for our needs. Much better then new implementation of the models to be able to track versions manually...

**Comment by AriMeidan** [comment]
Ok, i'll check it out.

**Comment by Nagasaki45** [comment]
As Udi said, django-reversion is too heavy solution. We will add a new model to the database (maybe in a separate app). Add it also to the system description doc.
